name: 414perspective
favicon: null
layout_spectrum: 0.99749
typography_spectrum: 0.75461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c3c3c3'
    - '#293948'
    - '#626d7b'
    - '#c58d27'
  brandStrength: 0.1875
  lightness: 0.5436392652336508
  saturation: 0.6276970107574016
  rhythmicContrast: 0.3199650659225881
purpose: []
