name: 414perspective
favicon: null
layout_spectrum: 1
typography_spectrum: 0.433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000d1c'
    - '#00f3fd'
    - '#ff0026'
    - '#ff8937'
  brandStrength: 0.875
  lightness: 0.5436392652336508
  saturation: 0.6276970107574016
  rhythmicContrast: 0.3199650659225881
purpose: []
